/* ============================================================
   雷特娛樂官網 data.js — 資料檔(改內容只需動這裡)
   1. P         全站圖片(base64:42 位 KOL 照片、首屏 Banner 桌機/手機版)
   2. KOL_XD / KOL_GREEN / KOL_PINKIE / KOL_SOUTH / KOL_ASTER / KOL_ZMN → KOL_DATA
      每位:{n 名稱, img 照片, intro 簡介, tags 標籤, links 社群連結}
      links 平台鍵:tw=Twitch yt=YouTube fb=Facebook ig=Instagram tk=TikTok x=X
   3. BRANDS    六廠牌(id / 中英名 / 品牌色 / Logo / 業務信箱)
   ============================================================ */

/* ================= Data ================= */
const P = {"roger_h": "assets/media/6579e108afef1db2.webp", "nl_h": "assets/media/aff7aeb8ee335aa4.webp", "hageng_h": "assets/media/252e9fa48bb61b9a.webp", "roger": "assets/media/0b376e6d8abc3e69.webp", "nl": "assets/media/f892d2eaf5fba2df.webp", "hageng": "assets/media/1ce638fe9ff2c823.webp", "eason": "assets/media/2c16f139b095e055.webp", "mmd": "assets/media/75c920b87873e586.webp", "vivi": "assets/media/174299427bd80d96.webp", "yuexi": "assets/media/dc38d4d0af48ebba.webp", "kent": "assets/media/ea61f9178d661505.webp", "asen": "assets/media/b436c4af55a036d1.webp", "tomi": "assets/media/0ea287c02885f1c5.webp", "dantou": "assets/media/cef159b7a2937ff5.webp", "xuexi": "assets/media/bb1bb19cd27313e7.webp", "kuipi": "assets/media/13795c3522da033a.webp", "zod": "assets/media/8f06b4510cefc892.webp", "xiaoliang": "assets/media/beee2465fe3ebd3d.webp", "xiaoyun": "assets/media/ee6664b3fd8834d8.webp", "xiaohu": "assets/media/ae4ec12ae17e1ab9.webp", "latte": "assets/media/11e5d4b13bd1dee3.webp", "lvcha": "assets/media/493bb4140c7aa3bc.webp", "kmomo": "assets/media/57b18c55a5e751aa.webp", "wuwei": "assets/media/e5aa8db517e2375c.webp", "sandeng": "assets/media/34b169c15c7828b7.webp", "xiaolin": "assets/media/c5b5e8a0822e7481.webp", "luyi": "assets/media/f8e4120b885a6866.webp", "guaierzi": "assets/media/e2ca921b1e283931.webp", "peipei": "assets/media/60642568147282d9.webp", "feizhai": "assets/media/1cda508f4f8cbc02.webp", "overload": "assets/media/cd7a90b6217452c5.webp", "lexis": "assets/media/0867e5ccbeb17b30.webp", "ko": "assets/media/9b078382525f431e.webp", "tobi": "assets/media/30e6ff10e7b60385.webp", "xinan": "assets/media/54a4ad0434b84ebb.webp", "douya": "assets/media/4ce348f1bf4508f9.webp", "atu": "assets/media/920fa742f384df96.webp", "xuexue": "assets/media/dcb02966c5ad0622.webp", "lvbao": "assets/media/ebd9e8de2a8260f0.webp", "jiandao": "assets/media/72bd12113fbbf901.webp", "leggy": "assets/media/3b81b3ded4698411.webp", "niaoshi": "assets/media/1fa69ea8737aeda7.webp", "erou": "assets/media/04a2a6ef15122e31.webp", "banner_pc": "assets/media/ed7e2161d481ab04.webp", "banner_m": "assets/media/dfd9917a2eeff35c.webp", "fauster": "assets/media/61b322aee5602a55.webp", "ludens": "assets/media/9e3b9a80f3cd17ad.webp"};
/* KOL 資料(名稱/簡介/標籤依 2026 品牌資料內部總表;links 依「社群連結校正版」填入) */
const KOL_XD = [
  {n:"羅傑 Roger", img:P.roger, intro:"Twitch流量惡魔,迷因製造機,一舉一動都極有可能成為近期社群熱門迷因話題,一句沒有要抽GOGORO紅破全網", tags:["卡牌","MOBA","ACG"], links:{tw:"https://www.twitch.tv/roger9527",yt:"https://www.youtube.com/channel/UCiEm9noegBIb-AzjqpxKffA",fb:"https://www.facebook.com/Roger95279527"}},
  {n:"NL", img:P.nl, intro:"前LOL選手,台灣唯一世界賽五殺紀錄,擅長MMORPG、SLG等長線經營遊戲,私人FB社團突破6萬人,粉絲凝聚力極高。", tags:["MOBA","SLG","商品合作"], links:{tw:"https://www.twitch.tv/never_loses",yt:"https://www.youtube.com/channel/UCRdJzOsu4MwKmY04vfAIDHw",fb:"https://www.facebook.com/NeVeRLosEs",ig:"https://www.instagram.com/nln1nl/"}},
  {n:"哈耿", img:P.hageng, intro:"Twitch少有技術型女實況主,2026 Monster Energy年度合作夥伴,擅長FPS、ARPG等大作。", tags:["FPS","ARPG","3C開箱"], links:{tw:"https://www.twitch.tv/ennaouii",yt:"https://www.youtube.com/channel/UCSfEJ-GsAQeet-sua7gQ5PA",fb:"https://www.facebook.com/profile.php?id=100082746162363",ig:"https://www.instagram.com/ennawei/"}},
  {n:"EASON", img:P.eason, intro:"擅長各類家機遊戲,Steam獨立遊戲遊玩經驗豐富,極度擅長運動類及寶可夢系列遊戲。", tags:["運動類","集換式卡牌","獨立遊戲"], links:{tw:"https://www.twitch.tv/m989876525",yt:"https://www.youtube.com/@eason9898",fb:"https://www.facebook.com/Egod9898",ig:"https://www.instagram.com/eason9898/"}},
  {n:"MMD", img:P.mmd, intro:"客群男女老少通吃,與美女主播搭配往往能引起話題,在MMORPG、ACG遊戲與觀眾互動頻繁,其代抽系列企劃受到實況觀眾喜愛。", tags:["MMORPG","ACG","MOBA"], links:{tw:"https://www.twitch.tv/yulihong22",yt:"https://www.youtube.com/@yulihong22",fb:"https://www.facebook.com/MMDlihong",ig:"https://www.instagram.com/yulihong22/"}},
  {n:"Vivi 芝衣", img:P.vivi, intro:"全方位女實況主,極具節目效果,積極參與各類連動及社群賽事,實況多人連動效果佳", tags:["ACG","競技","MOBA"], links:{tw:"https://www.twitch.tv/vivi0z1",yt:"https://www.youtube.com/@vivi0z1",fb:"https://www.facebook.com/vivi0z1",ig:"https://www.instagram.com/vivi0z1/",tk:"https://www.tiktok.com/@vivi0z1"}},
  {n:"月希", img:P.yuexi, intro:"Twitch付費訂閱數於2023年10月、2026年8月全球排名第四,70000訂閱打破亞洲最高紀錄,實況內容多元,涵蓋生活、遊戲、企劃等各面向,亦熟悉早期經典單機遊戲類別。", tags:["格鬥","主持人","魂系","3C開箱"], links:{tw:"https://www.twitch.tv/tsukilin",yt:"https://www.youtube.com/@tsukitsuki1226",fb:"https://www.facebook.com/tsuki1226",ig:"https://www.instagram.com/lintsuki/"}},
  {n:"Kant 肯特", img:P.kent, intro:"以專業遊戲技術為名,擅長製作遊戲攻略及教學影片,2026最大FPS實況賽事「鱷魔盃」主辦人。", tags:["FPS","ARPG","魂系"], links:{tw:"https://www.twitch.tv/kant0211",yt:"https://www.youtube.com/@Kant0211",fb:"https://www.facebook.com/Kant0211",ig:"https://www.instagram.com/kant0211/"}},
  {n:"阿森", img:P.asen, intro:"以專業的技術與分析聞名,曾任MOBA與FPS職業隊教練,同時深度鑽研各類3C電腦周邊配件,隨時掌握最新硬體資訊,開箱影片合作首選之一", tags:["3C開箱","FPS","MOBA","SLG"], links:{tw:"https://www.twitch.tv/assentw",yt:"https://www.youtube.com/@AsSenFPS",fb:"https://www.facebook.com/AsSeNlol",ig:"https://www.instagram.com/assen666/"}},
  {n:"偷米 Virtual", img:P.tomi, intro:"擅長於遊戲策略分析,找出遊戲的最佳解法並進行破關與競賽,且擅長各類型音GAME並熟悉ACG生態。", tags:["集換式卡牌","養成式RPG","音Game"], links:{tw:"https://www.twitch.tv/tommy181933",yt:"https://www.youtube.com/@virtual4492",fb:"https://www.facebook.com/tommy181933",ig:"https://www.instagram.com/virtual626/"}},
  {n:"蛋頭BG8LOCC", img:P.dantou, intro:"台灣人氣饒舌歌手,擁有10年以上音樂創作經歷,且對於各類家機及Steam系列大作皆有深度研究,擅長進行遊戲及音樂跨界合作。", tags:["音樂創作","獨立遊戲","3A"], links:{tw:"https://www.twitch.tv/thaeiht1",yt:"https://www.youtube.com/@thaEiht1",fb:"https://www.facebook.com/thaeiht1",ig:"https://www.instagram.com/thaeiht1/",tk:"https://www.tiktok.com/@thaeiht1"}},
  {n:"薛喜 Shaxy", img:P.xuexi, intro:"以無厘頭和風趣的搞怪風格吸引觀眾,同時擁有強大的遊戲學習能力,在卡牌、MOBA兩類遊戲中皆達到玩家前5%排名成就。", tags:["MOBA","卡牌","ARPG"], links:{tw:"https://www.twitch.tv/qq7925168",yt:"https://www.youtube.com/@%E5%A4%A9%E6%A2%AF%E5%B0%8F%E6%97%8B%E9%A2%A8%E8%96%9B%E5%96%9C",fb:"https://www.facebook.com/qq7925168"}},
  {n:"Krapy 虧皮", img:P.kuipi, intro:"現FPS賽事觀賽第一大台,由他實況進行的觀賽實況流量總是能輕鬆超過賽事主台,實況圈內公認的第一帥哥、把妹高手,同時幽默風趣的實況風格深受觀眾喜愛。", tags:["Co-Stream","FPS","主持人"], links:{tw:"https://www.twitch.tv/krapycoco",yt:"https://www.youtube.com/@krapy4754",fb:"https://www.facebook.com/Krapyliao",ig:"https://www.instagram.com/krapyliao/",tk:"https://www.tiktok.com/@krapycoco"}}
];
/* 綠光娛樂 6 位 */
const KOL_GREEN = [
  {n:"ZOD", img:P.zod, intro:"前職業電競教練與現役頂尖賽評,具深厚遊戲專業。幽默犀利口條鮮明,擅長創造直播話題效果。深耕英雄聯盟社群,核心玩家受眾黏著度高。", tags:["電競專業","主持","MOBA"], links:{tw:"https://www.twitch.tv/zod0416",yt:"https://www.youtube.com/@zod7174",fb:"https://www.facebook.com/zodlolz"}},
  {n:"小亮", img:P.xiaoliang, intro:"前英雄聯盟職業選手,從MOBA遊戲到派對型遊戲都有涉獵,以自然幽默的風格、親切互動以及精彩的遊戲操作,深受觀眾喜愛,也經常參與各類協作直播,無論是娛樂連動或是專業教學都能勝任。", tags:["MOBA","ARPG","SLG"], links:{tw:"https://www.twitch.tv/liang_0714",yt:"https://www.youtube.com/@liang7437",fb:"https://www.facebook.com/Liang0714",ig:"https://www.instagram.com/liang.7.14"}},
  {n:"小雲寶寶", img:P.xiaoyun, intro:"曾任LOL女子戰隊選手,遊戲上手速度極快,在2026參與爐石戰記節目,在兩週內從零開始學習並打上遊戲內最高牌位,亦擅長與粉絲長時間共同經營遊戲。", tags:["MOBA","卡牌","養成經營"], links:{tw:"https://www.twitch.tv/babybaby1111",yt:"https://www.youtube.com/@%E5%B0%8F%E9%9B%B2%E5%AF%B6%E5%AF%B6",fb:"https://www.facebook.com/baby19951111",ig:"https://www.instagram.com/baby19951111/"}},
  {n:"晓嫭(小虎)", img:P.xiaohu, intro:"以嗆辣風格與觀眾進行互動,時常跟觀眾分享遊戲、日常及熱門影片,擅長各類MMORPG、養成類放置手遊等長時間養成遊戲。", tags:["SLG","MMORPG","養成經營"], links:{tw:"https://www.twitch.tv/siaohu_0124",yt:"https://www.youtube.com/@siaohu",fb:"https://www.facebook.com/siaohu0124",ig:"https://www.instagram.com/siaohu_0124"}},
  {n:"絕世拿鐵", img:P.latte, intro:"現任聯盟戰棋職業選手,策略類型遊戲天賦極高,善於各類需高強度思考的策略型遊戲。", tags:["解謎","策略","卡牌"], links:{tw:"https://www.twitch.tv/jazlatte",yt:"https://www.youtube.com/@%E7%B5%95%E4%B8%96%E6%8B%BF%E9%90%B5",fb:"https://www.facebook.com/lattetft",ig:"https://www.instagram.com/lattetft/"}},
  {n:"綠茶", img:P.lvcha, intro:"直言不諱的風格擄獲大批粉絲,更讓觀眾親切喊他「茶哥/茶爸」。遊戲涉獵範圍極廣,在MOBA、卡牌、ACG、運動、ARPG、策略類遊戲皆表現良好,讓他成為一位什麼都玩、什麼都懂、什麼都能聊的萬能型實況主!", tags:["策略","MOBA","卡牌"], links:{tw:"https://www.twitch.tv/greentea",yt:"https://www.youtube.com/@GreenTeaks99",fb:"https://www.facebook.com/GreenTeaLOL",ig:"https://www.instagram.com/greenteaahq"}}
];
/* 拼經紀娛樂 10 位 */
const KOL_PINKIE = [
  {n:"許摸摸KMOMO", img:P.kmomo, intro:"前《Overwatch》職業電競選手,現為賽事主播、賽評及遊戲實況主。擁有深厚的競技遊戲背景與專業分析能力,內容兼具專業性與娛樂性,深受核心玩家與電競族群喜愛。", tags:["遊戲","實況主","退役電競選手","主播賽評"], links:{tw:"https://www.twitch.tv/kmomo_0512",yt:"https://www.youtube.com/@kmomo0512",fb:"https://www.facebook.com/KMOMO512",ig:"https://www.instagram.com/kmomo0512/",tk:"https://www.tiktok.com/@kmomo_0512"}},
  {n:"WuWei無為", img:P.wuwei, intro:"以 FPS 遊戲內容起家,兼具遊戲實況、產品開箱與娛樂互動等多元創作類型。憑藉直率自然、幽默接地氣的表達風格,成功累積忠實觀眾群。內容涵蓋熱門遊戲體驗、3C 周邊開箱及生活分享,擁有穩定的社群影響力與粉絲黏著度。", tags:["遊戲","實況主","開箱","影音創作者"], links:{tw:"https://www.twitch.tv/wuweichannel",yt:"https://www.youtube.com/@WuWei",fb:"https://www.facebook.com/wuweigaming",tk:"https://www.tiktok.com/@wuwei19970418"}},
  {n:"小三登", img:P.sandeng, intro:"新生代遊戲娛樂創作者,以自然真誠、不做作的互動風格累積穩定觀眾群。內容橫跨遊戲實況、生活分享與 3C 科技開箱,擅長打造貼近年輕族群的話題內容,具備良好的成長潛力與品牌合作彈性。", tags:["遊戲","實況主","開箱","影音創作者"], links:{tw:"https://www.twitch.tv/a1chenb",yt:"https://www.youtube.com/@a1chenb",ig:"https://www.instagram.com/1chen.20/"}},
  {n:"小霖XiaoLin", img:P.xiaolin, intro:"前《Garena 傳說對決》職業電競選手兼遊戲實況主,以幽默風趣且極具個人特色的直播風格受到粉絲喜愛。擅長結合高端操作與娛樂效果,透過鮮明梗文化與自然互動建立高度黏著的粉絲社群,在年輕遊戲族群中擁有穩定影響力。", tags:["遊戲","實況主"], links:{yt:"https://www.youtube.com/@XiaoLin1122",fb:"https://www.facebook.com/profile.php?id=100053120389464",ig:"https://www.instagram.com/xiaolin_1122/",tk:"https://www.tiktok.com/@xiaolin1122"}},
  {n:"嚕乙 luyee", img:P.luyi, intro:"遊戲與生活內容創作者,形象自然親切,擁有良好的粉絲互動能力。內容涵蓋遊戲實況、日常分享及品牌合作,擅長以真實生活視角創造共鳴,建立高信任度的社群關係。", tags:["遊戲","實況主","開箱","影音創作者"], links:{tw:"https://www.twitch.tv/luyee_1004",yt:"https://www.youtube.com/@luyee_1004",ig:"https://www.instagram.com/luyee_10.04/"}},
  {n:"乖兒子 GoodSon", img:P.guaierzi, intro:"遊戲與生活型創作者,以親民自然、幽默搞笑的個人特色深受粉絲喜愛。內容涵蓋遊戲體驗、3C 科技、生活開箱及品牌合作,擅長透過真實體驗分享建立觀眾信任感,擁有高互動率與強大粉絲黏著度。", tags:["遊戲","實況主","開箱","影音創作者"], links:{tw:"https://www.twitch.tv/goodson0706",yt:"https://www.youtube.com/@goodson0706",fb:"https://www.facebook.com/GoodSon0706",ig:"https://www.instagram.com/goodson0706/",tk:"https://www.tiktok.com/@goodson0706"}},
  {n:"佩佩豬伯爵PpdbJ", img:P.peipei, intro:"前《特戰英豪 VALORANT》職業選手,現為賽事賽評、教練及活動主持人。具備專業競技背景與優秀口條能力,擅長品牌活動主持、電競賽事轉播、遊戲內容推廣及現場互動,兼具專業形象與娛樂效果。", tags:["遊戲","實況主","主播賽評","主持人","開箱","影音創作者"], links:{tw:"https://www.twitch.tv/ppdbj",yt:"https://www.youtube.com/@PpdbJ0320",fb:"https://www.facebook.com/profile.php?id=100065295348339",ig:"https://www.instagram.com/ppdbj0320/",tk:"https://www.tiktok.com/@ppdbj"}},
  {n:"肥宅MS", img:P.feizhai, intro:"以獨樹一幟的說書風格深受觀眾喜愛,長期深耕動漫、ACG 文化與遊戲相關內容。擅長將複雜的作品背景、角色設定與劇情脈絡轉化為生動易懂的敘事內容,兼具娛樂性與資訊深度。內容涵蓋動漫解析、遊戲體驗、熱門話題討論及社群互動,累積穩定且高黏著度的核心粉絲族群。", tags:["遊戲","動漫","ACG","影音創作者"], links:{yt:"https://www.youtube.com/channel/UCBOBS5RdHd2Owytoj4PqPqA",fb:"https://www.facebook.com/ms0437724/",ig:"https://www.instagram.com/feizhaims/",tk:"https://www.tiktok.com/@otakums00"}},
  {n:"超負荷", img:P.overload, intro:"Twitch 指標型遊戲實況主,以熱血直率、幽默風趣的風格深受玩家喜愛。長期深耕《英雄聯盟》內容,擁有高度社群影響力與忠誠粉絲基礎,擅長遊戲推廣、品牌合作及大型活動曝光。", tags:["遊戲","實況主"], links:{tw:"https://www.twitch.tv/sam1268",yt:"https://www.youtube.com/@overloadtw",fb:"https://www.facebook.com/overloadtw",ig:"https://www.instagram.com/overloadtw/"}},
  {n:"雷克獅Rex", img:P.lexis, intro:"電競主播、賽評及活動主持人,擁有豐富大型賽事與品牌活動經驗。以自信熱血的風格與穩健台風著稱,擅長帶動現場氣氛與串聯觀眾情緒,是兼具專業度與娛樂性的全方位主持人才。", tags:["遊戲","實況主","開箱","影音創作者"], links:{tw:"https://www.twitch.tv/rexlin777",yt:"https://www.youtube.com/@rexderyt",fb:"https://www.facebook.com/rexesportlife/"}}
];
/* 南大俠娛樂 8 位 */
const KOL_SOUTH = [
  {n:"Ko0416", img:P.ko, intro:"擁有前 PUBG 職業選手背景,兼具高水準遊戲操作與強烈綜藝效果,擅長結合抽卡、競技等遊戲內容,核心玩家受眾集中且具高度社群號召力。", tags:["FPS","二次元","3A"], links:{tw:"https://www.twitch.tv/ko0416",yt:"https://www.youtube.com/@Koko0416",fb:"https://www.facebook.com/Ko0416/",ig:"https://www.instagram.com/ko0416_"}},
  {n:"托比", img:P.tobi, intro:"具高度親和力與社群凝聚力,擅長生活雜談及跨界企劃,連續兩年擔任 WirForce 女團 Cover 舞蹈活動總召集,具優異整合力與話題創造能力。", tags:["跳舞音樂","MOBA","休閒"], links:{tw:"https://www.twitch.tv/tobe841023",yt:"https://www.youtube.com/@tobe3345",fb:"https://www.facebook.com/tobe841023",ig:"https://www.instagram.com/tobe841023/"}},
  {n:"蔣西南", img:P.xinan, intro:"近年最具綜藝爆發力的核心實況主之一。以充滿渲染力的情緒張力與即興迷因創造能力,將遊戲過程轉化為高互動性的娛樂饗宴。成功建立起高黏著度且活躍的社群生態圈,是品牌尋求話題擴散與深度社群連結的指標性創作者。", tags:["FPS","獨立遊戲","3A"], links:{tw:"https://www.twitch.tv/kr1stw",yt:"https://www.youtube.com/@Kr1stw",fb:"https://www.facebook.com/kr1stw69/",ig:"https://www.instagram.com/kris_chen7410/"}},
  {n:"豆芽妹", img:P.douya, intro:"以自然親和的鄰家氣質與幽默口條著稱,兼具遊戲實力與直播效果,擅長魂類、動作及射擊遊戲,細膩互動與臨場反應深受觀眾喜愛。", tags:["FPS","魂系動作","二次元"], links:{tw:"https://www.twitch.tv/qqdoya",yt:"https://www.youtube.com/@qqdoya222",fb:"https://www.facebook.com/profile.php?id=100070976568744",ig:"https://www.instagram.com/zo.uee"}},
  {n:"阿土", img:P.atu, intro:"具職業電競選手與教練背景,擁有深厚遊戲素養與專業內容解析力,且擅長策略與經營類遊戲,近期更取得SLG《信長之野望:真戰》賽季冠軍佳績。", tags:["MMORPG","SLG","攻略"], links:{tw:"https://www.twitch.tv/q158688920",yt:"https://www.youtube.com/@atulolz5550",fb:"https://www.facebook.com/Atulolz183",ig:"https://www.instagram.com/atulolz/"}},
  {n:"雪雪", img:P.xuexue, intro:"兼具遊戲天分與陪伴感的 VTuber,理解力與遊戲上手速度出色,能駕馭多種類型遊戲,與西南連動默契十足,經常創造亮眼綜藝效果。", tags:["FPS","MOBA","動作"], links:{tw:"https://www.twitch.tv/yukkkkiouo",yt:"https://www.youtube.com/@yukkkkiouo",ig:"https://www.instagram.com/yukkkkiouo/",x:"https://x.com/yukkkkiouo"}},
  {n:"綠寶", img:P.lvbao, intro:"戶外實況領域具代表性的創作者,以真性情互動與高社群黏著度著稱,同時挑戰動作遊戲等多元內容,兼具實境轉播魅力與遊戲娛樂效果。", tags:["FPS","日系遊戲","SRPG"], links:{tw:"https://www.twitch.tv/z60411",yt:"https://www.youtube.com/@z60411",fb:"https://www.facebook.com/Greenbow0320",ig:"https://www.instagram.com/greenbow0320/"}},
  {n:"簡到槍", img:P.jiandao, intro:"深耕 PC 遊戲實況領域,以鮮明個人風格與即興搞笑能力著稱,擅長從遊戲互動創造爆笑名場面,《Rust》相關內容更曾多次引發社群熱議。", tags:["FPS","生存","動作"], links:{tw:"https://www.twitch.tv/dd87878",yt:"https://www.youtube.com/@dd87878",fb:"https://www.facebook.com/dd87878",ig:"https://www.instagram.com/ddd8787878/"}}
];
/* 艾斯特娛樂 3 位 */
const KOL_ASTER = [
  {n:"Leggy", img:P.leggy, intro:"1. 核心粉絲黏著度高,陪伴型社群特質強:長期開台累積出穩定的核心觀眾,實況風格著重聊天、互動與陪伴感,加上鮮明個性與獨特笑點,容易形成「熟客型」社群,粉絲對本人及參與企劃都有較深的情感連結。\n2. 資深實況主,具 LNG 團體辨識度:Leggy 為早期 LNG 實況圈成員之一,累積多年實況經驗與固定觀眾基礎,個人風格鮮明,在資深實況觀眾中具有一定辨識度與熟悉感。\n3. 角色塑造能力強,遊戲內容具故事性:除了一般遊戲與聊天實況,也曾深度參與《自由新鎮》等 GTA RP 企劃,透過角色展現角色扮演與敘事能力,能讓觀眾不只是看遊戲,更會持續追角色與劇情發展。", tags:["遊戲","實況主","影音創作者"], links:{tw:"https://www.twitch.tv/rekileggy",yt:"https://www.youtube.com/channel/UC2pAstZuQKWTYtY0TSkAmTQ",fb:"https://www.facebook.com/LeggyReki/",ig:"https://www.instagram.com/ym78305/"}},
  {n:"鳥屎", img:P.niaoshi, intro:"1. 劇場演員底蘊,表演張力十足:本身是專業劇場演員、導演,擁有完整戲劇訓練與豐富舞台經驗,無論語氣、肢體還是臨場反應,都自帶強烈的表演張力與感染力。\n2. 行走的迷因製造機,無厘頭又超有梗:極具戲劇性的反應,常常在意想不到的地方製造笑點。幽默不是刻意鋪梗,而是靠臨場反應自然長出迷因,堪稱「迷因製造機」,其幽默風趣的實況風格也是他受到關注的重要特色。\n3. 跨足生活 × 遊戲的高知名度實況主:近期更憑藉高娛樂性的短影音內容創造亮眼流量,持續擴大圈外觸及與社群聲量。", tags:["遊戲","實況主","主持","影音創作者"], links:{tw:"https://www.twitch.tv/scspple7545",yt:"https://www.youtube.com/@niaws-5352",fb:"https://www.facebook.com/LNGniaws/",ig:"https://www.instagram.com/scspple7545/"}},
  {n:"鵝肉麵", img:P.erou, intro:"1. 圖文敘事型創作者,風格辨識度高:以圖文動畫＋故事敘事為核心創作形式,透過鮮明角色、幽默旁白與生活觀察建立個人風格。題材涵蓋生活故事、美國生活、遊戲與英文等,在不同平台都有延伸內容。\n2. 「美國故事」系列最具代表性:曾在美國生活超過十年,擅長將自身的美國生活經驗轉化成有趣、具共鳴感的圖文動畫;「美國故事/美國生活」也成為頻道最具代表性的內容主題之一,兼具文化差異、生活觀察與幽默感。\n3. 核心受眾黏著度高,角色 IP 感強:長期以固定的圖文角色與敘事風格累積觀眾,讓粉絲不只追單一主題,更是因為喜歡創作者本身的世界觀與幽默感而持續觀看,具備穩定的核心粉絲與高黏著度社群。", tags:["遊戲","圖文創作","影音創作者"], links:{yt:"https://www.youtube.com/@crispyfriedabc",fb:"https://www.facebook.com/crispyfriedabc/",ig:"https://www.instagram.com/crispyfriedabc/"}}
];
/* 賺馬逆娛樂 2 位(照片待補) */
const KOL_ZMN = [
  {n:"吹著魔笛的浮士德", img:P.fauster, intro:"遊戲產業評論觀察家,在二十年間寫出數百篇遊戲分析長文,本人亦曾任遊戲營運部門主管、海外商務負責人、獨立遊戲開發團隊顧問、整合行銷公司總經理、數位媒體企業董事長等職位。", tags:["深度評測","3C開箱","文字攻略"], links:{yt:"https://www.youtube.com/user/h98569856",fb:"https://www.facebook.com/h9856games?locale=zh_TW",ig:"https://www.instagram.com/faustusliving/"}},
  {n:"The Ludens", img:P.ludens, intro:"一座為熱愛ACGN 文化、理解敘事張力、並喜於深度討論的靈魂所打造的「媒體實驗室」,專門針對獨立遊戲、產業新聞、財務報告進行快速播送。", tags:["新聞媒體","遊戲新知","資訊快報"], links:{fb:"https://www.facebook.com/profile.php?id=61575565016815",x:"https://x.com/TheLudensMedia"}}
];
const KOL_DATA = {xd: KOL_XD, green: KOL_GREEN, pinkie: KOL_PINKIE, south: KOL_SOUTH, aster: KOL_ASTER, zmn: KOL_ZMN};
const L = {
  xd_b:"assets/media/18d550c47545caae.webp",
  south_b:"assets/media/a7a9c501281221c2.webp", south_c:"assets/media/7baee13e90e96384.webp",
  green_b:"assets/media/76fe4a70a1ded3c5.webp", green_c:"assets/media/30117cd4a9151e8b.webp",
  pinkie_b:"assets/media/7aa7a962de05283f.webp", pinkie_c:"assets/media/cce756dd6c104f8f.webp"
};
const BRANDS = [
  {id:"xd",    zh:"叉滴娛樂",   en:"XD ENTERTAINMENT", color:"#4197C5", email:"xdteam.sales@gmail.com",     logoB:L.xd_b,     logoC:null},
  {id:"green", zh:"綠光娛樂",   en:"GREENLIGHT",       color:"#1F8A5C", email:"greenlight777.bd@gmail.com",  logoB:L.green_b,  logoC:L.green_c},
  {id:"south", zh:"南大俠娛樂", en:"KKAJ",             color:"#B5382B", email:"kkaj.sales@gmail.com",       logoB:L.south_b,  logoC:L.south_c},
  {id:"pinkie", lightLogo:true,zh:"拼經紀娛樂", en:"PINKIE STUDIO",    color:"#E87DA9", email:"sales@pinkiestudio.info",    logoB:L.pinkie_b, logoC:L.pinkie_c},
  {id:"aster", zh:"艾斯特娛樂", en:"ASTER",            color:"#8E6BD9", email:"", logoB:null, logoC:null},
  {id:"zmn",   zh:"賺馬逆娛樂", en:"ZMN",              color:"#C8B818", email:"", logoB:null, logoC:null}
];
